<a href="https://colab.research.google.com/github/Kar3nOrtega/KarenOrtega/blob/main/numpypandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = np.array([5,12,4]) #arreglo tiene dimensiones de entrada
print(arr)
print(type(arr))
print(arr.shape)# tiene que ver con la capa de entrada

[ 5 12  4]
<class 'numpy.ndarray'>
(3,)


In [3]:
arr = np.zeros((3,3)) # o ones crea de unos
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arr =np.arange (1,100,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [5]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])  # cada lista una fila
arr2D





array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
result = arr2D > 3
result

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [7]:
arr_aux = arr2D.reshape(9,) #toma un arreglo con una domension y la reorganiza en otra dimension compatible

arr_aux

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.sum(arr_aux)
np.sum(arr_aux, axis=0)
np.sum(arr_aux, axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [12]:
city = pd.Series(['Popayan','Cali', 'Bogota' ])
temperatura = pd.Series([23, 28, 19])

print (temperatura)

0    23
1    28
2    19
dtype: int64


In [15]:
df_weather = pd.DataFrame ({'City': city, 'Temp': temperatura})
df_weather.head() #cabecera 5 primeros
df_weather.tail() #cola 5 ultimos


City  Temp
0  Popayan    23
1     Cali    28
2   Bogota    19

In [17]:
df_weather ['City']

0    Popayan
1       Cali
2     Bogota
Name: City, dtype: object

In [ ]:
df_weather ['City'] [2]

In [18]:
df_weather [0:2]

City  Temp
0  Popayan    23
1     Cali    28

In [19]:
df_weather.loc[:,['City']]

City
0  Popayan
1     Cali
2   Bogota

In [20]:
df_weather['Temp'] .apply(lambda T:T>20)

0     True
1     True
2    False
Name: Temp, dtype: bool

In [21]:
df_weather['Elevation'] = pd.Series([1693,1018,2640])
df_weather.head()

City  Temp  Elevation
0  Popayan    23       1693
1     Cali    28       1018
2   Bogota    19       2640

In [23]:
df_aux = df_weather.drop(labels='Elevation', axis=1)
df_aux.head

<bound method NDFrame.head of       City  Temp
0  Popayan    23
1     Cali    28
2   Bogota    19>

In [26]:
array = df_aux.to_nompy()
array

AttributeError: 'DataFrame' object has no attribute 'to_nompy'

In [27]:
arr = np.array([[3,5], [1,5],[4,5]])
df = pd.DataFrame (arr)
df.head()
df = pd.DataFrame(arr, columns = ['col1','col2'])
df.head()

col1  col2
0     3     5
1     1     5
2     4     5

In [28]:
data = pd.read_txt("taller.txt", header=0)
data.head()

AttributeError: module 'pandas' has no attribute 'read_txt'